# Generated by Django 4.2.21 on 2025-07-08 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbienteEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.ambiente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Apps.equipamento')),
            ],
            options={
                'unique_together': {('ambiente', 'equipamento')},
            },
        ),
        migrations.AddField(
            model_name='ambiente',
            name='equipamentos',
            field=models.ManyToManyField(related_name='ambientes', through='Apps.AmbienteEquipamento', to='Apps.equipamento'),
        ),
    ]
