# Generated by Django 4.2.21 on 2025-07-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_ambienteequipamento_ambiente_equipamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cep',
            field=models.CharField(default=0, max_length=9, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(default=0, max_length=14, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_matricula',
            field=models.CharField(default=0, max_length=20, unique=True, verbose_name='Matrícula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_residencia',
            field=models.CharField(default=0, max_length=10, verbose_name='Número da Residência'),
            preserve_default=False,
        ),
    ]
